const designContexts = [
  [
    "restaurante",
    "Restaurante",
    "Lora",
    "Manrope",
    "Una serif cálida en títulos con una sans clara para menú, reservas y precios.",
    "Comprueba legibilidad del menú y números; no conviertas todo en una carta ornamentada.",
  ],
  [
    "tecnologia",
    "Tecnología / app",
    "Space Grotesk",
    "Inter",
    "Títulos con carácter y cuerpo neutral para interfaz.",
    "Evita tamaños pequeños y pesos ligeros en paneles densos.",
  ],
  [
    "lujo",
    "Lujo / moda",
    "Playfair Display",
    "Manrope",
    "Contraste editorial en títulos y cuerpo sobrio.",
    "Lujo no requiere letra ilegible ni texto con contraste bajo.",
  ],
  [
    "infantil",
    "Infantil / diversión",
    "Manrope",
    "Inter",
    "Formas abiertas, pesos claros y ritmo amistoso.",
    "La diversión puede venir del color y la composición; no hace falta una fuente difícil de leer.",
  ],
  [
    "legal",
    "Legal / corporativo",
    "Lora",
    "Inter",
    "Tradición controlada con claridad de interfaz.",
    "Contratos y textos largos necesitan tamaños cómodos y buena interlínea.",
  ],
  [
    "deporte",
    "Deportes / fitness",
    "Bebas Neue",
    "Inter",
    "Titulares enérgicos y condensados con cuerpo funcional.",
    "Usa display en titulares breves, no en instrucciones ni párrafos.",
  ],
  [
    "salud",
    "Salud / bienestar",
    "Manrope",
    "Inter",
    "Textos abiertos, tranquilos y predecibles.",
    "El contenido importante no debe depender de una estética tenue.",
  ],
  [
    "inmobiliaria",
    "Inmobiliaria",
    "Space Grotesk",
    "Manrope",
    "Presencia en titulares y claridad en detalles del inmueble.",
    "Comprueba precios, unidades, direcciones y filtros.",
  ],
  [
    "editorial",
    "Editorial / blog",
    "Lora",
    "Inter",
    "Voz editorial y contraste entre lectura y navegación.",
    "Limita la longitud de línea y distingue citas, pies y subtítulos.",
  ],
  [
    "boda",
    "Boda / evento",
    "Dancing Script",
    "Manrope",
    "Un acento ceremonial en títulos, información práctica muy clara.",
    "Fechas, direcciones y confirmaciones deben usar una fuente sencilla.",
  ],
  [
    "arte",
    "Arte / creativo",
    "Abril Fatface",
    "Manrope",
    "Un título expresivo con un cuerpo que deje respirar las obras.",
    "La tipografía no debería competir continuamente con el contenido.",
  ],
  [
    "tienda",
    "Tienda / comercio",
    "Inter",
    "Manrope",
    "Jerarquía clara para productos y decisiones de compra.",
    "No uses personalidad como excusa para ocultar precios o información.",
  ],
  [
    "educacion",
    "Educación",
    "Zilla Slab",
    "Inter",
    "Carácter de publicación con lectura sencilla.",
    "Prueba símbolos, acentos, fórmulas y textos largos.",
  ],
  [
    "gastronomia",
    "Cafetería / artesanía",
    "Lora",
    "Manrope",
    "Calidez en títulos con detalles de producto claros.",
    "Una manuscrita puede ser acento breve, no toda la interfaz.",
  ],
  [
    "social",
    "Proyecto social",
    "Manrope",
    "Inter",
    "Claridad y cercanía sin solemnidad excesiva.",
    "El mensaje y el público importan más que estereotipos de tipografía.",
  ],
];
const designTones = [
  [
    "rojo",
    "Rojo",
    "#bd2633",
    "Intenso, enérgico, urgente.",
    "Puede asociarse con pasión, peligro o promoción.",
    "Úsalo para acentos claros; no conviertas toda la interfaz en una alerta.",
    "Coca-Cola y Netflix usan rojo en sus identidades.",
    "https://www.coca-cola.com/es/es/about-us/faq/por-que-el-color-corporativo-de-coca-cola-es-rojo",
  ],
  [
    "azul",
    "Azul",
    "#244cb4",
    "Sereno, técnico, estable.",
    "Puede apoyar sensaciones de confianza o distancia.",
    "El azul por sí solo no convierte una marca en confiable.",
    "IKEA combina azul y amarillo en su identidad.",
    "https://www.ikea.com/ph/en/this-is-ikea/about-us/the-ikea-logo-history-and-design-pub55d85f50/",
  ],
  [
    "verde",
    "Verde",
    "#176c49",
    "Natural, equilibrado, activo.",
    "Puede sugerir bienestar, crecimiento o permiso.",
    "No todos los verdes parecen naturales; saturación y contexto importan.",
    "Spotify utiliza verde como color reconocible de marca.",
    "https://developer.spotify.com/documentation/design",
  ],
  [
    "amarillo",
    "Amarillo",
    "#f5cc39",
    "Luminoso, optimista, visible.",
    "Puede asociarse con energía y atención.",
    "Con texto blanco suele tener poco contraste; prueba texto oscuro.",
    "IKEA utiliza amarillo junto con azul.",
    "https://www.ikea.com/ph/en/this-is-ikea/about-us/the-ikea-logo-history-and-design-pub55d85f50/",
  ],
  [
    "naranja",
    "Naranja",
    "#b94e13",
    "Cálido, accesible, dinámico.",
    "Puede sugerir cercanía o actividad.",
    "En exceso puede perder jerarquía: reserva un papel claro.",
    "Ejemplo ficticio: una escuela de cocina.",
    "",
  ],
  [
    "violeta",
    "Violeta",
    "#7541a8",
    "Imaginativo, singular, expresivo.",
    "Puede sugerir creatividad o sofisticación.",
    "No implica lujo automáticamente; comprueba tono y audiencia.",
    "Ejemplo ficticio: un estudio creativo.",
    "",
  ],
  [
    "rosa",
    "Rosa",
    "#b42b72",
    "Expresivo, amable, contemporáneo.",
    "Puede ser suave o contundente según saturación y luz.",
    "Evita limitarlo a un género: la voz de marca no depende de estereotipos.",
    "Ejemplo ficticio: un festival cultural.",
    "",
  ],
  [
    "negro",
    "Negro",
    "#202124",
    "Sobrio, contundente, concentrado.",
    "Puede apoyar lujo, tecnología o cultura.",
    "Grandes fondos oscuros requieren contraste y estados consistentes.",
    "Ejemplo ficticio: una galería de diseño.",
    "",
  ],
  [
    "blanco",
    "Blanco",
    "#ffffff",
    "Abierto, limpio, ligero.",
    "Puede transmitir calma y espacio.",
    "Necesita bordes y contraste; blanco no significa ausencia de diseño.",
    "Ejemplo ficticio: una clínica con interfaz clara.",
    "",
  ],
  [
    "tierra",
    "Tierra",
    "#80543b",
    "Cálido, material, artesanal.",
    "Puede recordar madera, café y materiales naturales.",
    "No fuerces beige a todos los proyectos: puede borrar contraste.",
    "Ejemplo ficticio: una marca de cerámica.",
    "",
  ],
];
const designPalettes = [
  ["restaurante", "Restaurante", "#fff9f1", "#f0dcc4", "#87361d"],
  ["tecnologia", "Tecnología / app", "#f6f8ff", "#e1e8fb", "#2746c7"],
  ["lujo", "Lujo / moda", "#fcfaf5", "#e8dfcc", "#594515"],
  ["infantil", "Infantil / diversión", "#fffdf4", "#fff0b0", "#9535a7"],
  ["legal", "Legal / corporativo", "#f7f9fb", "#dfe6ec", "#233e68"],
  ["deporte", "Deportes / fitness", "#f6f6f6", "#e0e4e8", "#be2828"],
  ["salud", "Salud / bienestar", "#f6fcf9", "#d8ede2", "#176449"],
  ["inmobiliaria", "Inmobiliaria", "#fafbf9", "#e2e9e1", "#365b3a"],
  ["editorial", "Editorial / blog", "#fffaf4", "#eee4d6", "#8a3922"],
  ["boda", "Boda / evento", "#fff9fb", "#efdee7", "#903458"],
  ["arte", "Arte / creativo", "#fbf8ff", "#e7defa", "#6843b2"],
  ["tienda", "Tienda / comercio", "#f8fafc", "#e0e8ef", "#174c83"],
  ["educacion", "Educación", "#fffdf7", "#e4eafa", "#334aae"],
  ["gastronomia", "Cafetería / artesanía", "#fff9f2", "#e8d8c6", "#76482c"],
  ["social", "Proyecto social", "#f8fcff", "#ddebfa", "#295c8a"],
];
